### ISSUE TITLE
How does the audio line-out switching work?

### ISSUE THREAD

**Issue by stowellt** [birdslikewires/openframe-kernel#1]
The README says there is a patch to make line-out switching work. Does this mean you can make the 3.5mm jack on the back output line-level audio instead of headphone level audio?

If this is the case, how do you go about switching it?

**Comment by andydvsn** [comment]
Sorry, just seen this; no, what this actually means is that plugging something in to that headphone output (if that is indeed what it is; I guess that makes more sense than a line level feed) will switch off the internal speaker. Without the patch the internal speaker just keeps on playing when a 3.5mm jack is plugged in.
